language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t bignose1flower/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bignose1flower/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-316216840977"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $aws_access_key
  secret_access_key: $aws_secret_key