language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t bignose1flower/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bignose1flower/docker-react npm run test -- --coverage